APP_VERSION = "0.1.0"
DEFAULT_APP_NAME = "DilliBites AI Service"

API_VERSION = "v1"
API_V1_PREFIX = "/api/v1"

ENV_FILE = ".env"
ENV_PREFIX = "AI_SERVICE_"

DEFAULT_ENVIRONMENT = "local"
ALLOWED_ENVIRONMENTS = ("local", "development", "test", "staging", "production")

DEFAULT_LOG_LEVEL = "INFO"
ALLOWED_LOG_LEVELS = ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")

DEFAULT_SERVER_HOST = "0.0.0.0"
DEFAULT_SERVER_PORT = 8000

DEFAULT_RATE_LIMIT_ENABLED = True
DEFAULT_GLOBAL_RATE_LIMIT = "100/minute"
HEALTH_RATE_LIMIT = "unlimited"

DEFAULT_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/dillibites"
DEFAULT_DATABASE_ECHO = False

DEFAULT_GROQ_BASE_URL = "https://api.groq.com/openai/v1"
DEFAULT_GROQ_API_KEY = ""
DEFAULT_GROQ_MODEL = "llama-3.1-8b-instant"
DEFAULT_GROQ_TIMEOUT_SECONDS = 30.0
DEFAULT_GROQ_MAX_RETRIES = 3
DEFAULT_GROQ_RETRY_BACKOFF_SECONDS = 0.5

DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "llama3.1:8b"
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 30.0
DEFAULT_OLLAMA_MAX_RETRIES = 3
DEFAULT_OLLAMA_RETRY_BACKOFF_SECONDS = 0.5

DEFAULT_CHROMA_PERSIST_DIRECTORY = ".chroma"
DEFAULT_CHROMA_COLLECTION_NAME = "reviews"
DEFAULT_CHROMA_DISTANCE_METRIC = "cosine"
ALLOWED_CHROMA_DISTANCE_METRICS = ("cosine", "l2", "ip")
